jobs:
  - name: 'run'
    public: true
    plan:
      - task: 'install'
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: maven }
         
          run:
            path: /bin/sh
            args:
              - -c
              - |
                dir
                ls
                mvn test
                echo cd ls
                echo cd dir